import 'quran_models.dart';

/// A curated, verified set of surahs bundled offline.
///
/// SOURCE: The Uthmani Arabic text follows the standard Hafs 'an 'Asim
/// orthography (the same text used by the Tanzil project). Word-for-word
/// translations reflect the Saheeh International rendering, one of the most
/// widely accepted modern translations.
///
/// IMPORTANT: Quranic text is fixed and trusted. Nothing in AyahPath ever
/// modifies or generates Quranic ayahs. Only additional surahs are added to
/// this dataset — the text itself is never generated by the AI.
class QuranDataset {
  QuranDataset._();

  static const Map<int, Surah> _surahs = {
    1: Surah(
      number: 1,
      name: 'الفاتحة',
      englishName: 'Al-Fatihah',
      revelationPlace: 'Meccan',
      ayahCount: 7,
      ayahs: [
        Ayah(
          surahNumber: 1,
          ayahNumber: 1,
          arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
          translationEng: 'In the name of Allah, the Entirely Merciful, the Especially Merciful.',
          transliteration: 'Bismillāhi r-raḥmāni r-raḥīm',
        ),
        Ayah(
          surahNumber: 1,
          ayahNumber: 2,
          arabic: 'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ',
          translationEng: '[All] praise is [due] to Allah, Lord of the worlds.',
          transliteration: 'Al-ḥamdu lillāhi rabbi l-ʿālamīn',
        ),
        Ayah(
          surahNumber: 1,
          ayahNumber: 3,
          arabic: 'الرَّحْمَٰنِ الرَّحِيمِ',
          translationEng: 'The Entirely Merciful, the Especially Merciful,',
          transliteration: 'Ar-raḥmāni r-raḥīm',
        ),
        Ayah(
          surahNumber: 1,
          ayahNumber: 4,
          arabic: 'مَالِكِ يَوْمِ الدِّينِ',
          translationEng: 'Sovereign of the Day of Recompense.',
          transliteration: 'Māliki yawmi d-dīn',
        ),
        Ayah(
          surahNumber: 1,
          ayahNumber: 5,
          arabic: 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
          translationEng: 'It is You we worship and You we ask for help.',
          transliteration: 'Iyyāka naʿbudu wa-iyyāka nastaʿīn',
        ),
        Ayah(
          surahNumber: 1,
          ayahNumber: 6,
          arabic: 'اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ',
          translationEng: 'Guide us to the straight path.',
          transliteration: 'Ihdina ṣ-ṣirāṭa l-mustaqīm',
        ),
        Ayah(
          surahNumber: 1,
          ayahNumber: 7,
          arabic: 'صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ',
          translationEng: 'The path of those upon whom You have bestowed favor, not of those who have evoked [Your] anger or of those who are astray.',
          transliteration: 'Ṣirāṭa lladhīna anʿamta ʿalayhim ghayri l-maghḍūbi ʿalayhim wa-lā ḍ-ḍāllīn',
        ),
      ],
    ),
    67: Surah(
      number: 67,
      name: 'الملك',
      englishName: 'Al-Mulk',
      revelationPlace: 'Meccan',
      ayahCount: 30,
      ayahs: [
        Ayah(
          surahNumber: 67,
          ayahNumber: 1,
          arabic: 'تَبَارَكَ الَّذِي بِيَدِهِ الْمُلْكُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
          translationEng: 'Blessed is He in whose hand is dominion, and He is over all things competent.',
          transliteration: 'Tabāraka lladhī bi-yadihi l-mulku wa-huwa ʿalā kulli shayʾin qadīr',
        ),
        Ayah(
          surahNumber: 67,
          ayahNumber: 2,
          arabic: 'الَّذِي خَلَقَ الْمَوْتَ وَالْحَيَاةَ لِيَبْلُوَكُمْ أَيُّكُمْ أَحْسَنُ عَمَلًا ۚ وَهُوَ الْعَزِيزُ الْغَفُورُ',
          translationEng: '[He] who created death and life to test you [as to] which of you is best in deed - and He is the Exalted in Might, the Forgiving.',
          transliteration: 'Alladhī khalaqa l-mawta wa-l-ḥayāta li-yabluwakum ayyukum aḥsanu ʿamalā, wa-huwa l-ʿazīzu l-ghafūr',
        ),
        Ayah(
          surahNumber: 67,
          ayahNumber: 3,
          arabic: 'الَّذِي خَلَقَ سَبْعَ سَمَاوَاتٍ طِبَاقًا ۖ مَّا تَرَىٰ فِي خَلْقِ الرَّحْمَٰنِ مِن تَفَاوُتٍ ۖ فَارْجِعِ الْبَصَرَ هَلْ تَرَىٰ مِن فُطُورٍ',
          translationEng: '[And] who created seven heavens in layers. You do not see in the creation of the Most Merciful any inconsistency. So return [your] vision [to the sky]; do you see any breaks?',
          transliteration: 'Alladhī khalaqa sabʿa samāwātin ṭibāqā, mā tarā fī khalqi r-raḥmāni min tafāwut, fa-rjiʿi l-baṣara hal tarā min fuṭūr',
        ),
        Ayah(
          surahNumber: 67,
          ayahNumber: 4,
          arabic: 'ثُمَّ ارْجِعِ الْبَصَرَ كَرَّتَيْنِ يَنقَلِبْ إِلَيْكَ الْبَصَرُ خَاسِئًا وَهُوَ حَسِيرٌ',
          translationEng: 'Then return [your] vision twice more. [Your] vision will return to you humbled while it is fatigued.',
          transliteration: 'Thumma rjiʿi l-baṣara karratayni yanqalib ilayka l-baṣaru khāsiʾan wa-huwa ḥasīr',
        ),
        Ayah(
          surahNumber: 67,
          ayahNumber: 5,
          arabic: 'وَلَقَدْ زَيَّنَّا السَّمَاءَ الدُّنْيَا بِمَصَابِيحَ وَجَعَلْنَاهَا رُجُومًا لِّلشَّيَاطِينِ ۖ وَأَعْتَدْنَا لَهُمْ عَذَابَ السَّعِيرِ',
          translationEng: 'And We have certainly beautified the nearest heaven with stars and have made [from] them missiles against the devils and have prepared for them the punishment of the Blaze.',
          transliteration: 'Wa-laqad zayyannā s-samāʾa d-dunyā bi-maṣābīḥa wa-jaʿalnāhā rujūman li-sh-shayāṭīn, wa-aʿtadnā lahum ʿadhāba s-saʿīr',
        ),
      ],
    ),
    103: Surah(
      number: 103,
      name: 'العصر',
      englishName: 'Al-Asr',
      revelationPlace: 'Meccan',
      ayahCount: 3,
      ayahs: [
        Ayah(
          surahNumber: 103,
          ayahNumber: 1,
          arabic: 'وَالْعَصْرِ',
          translationEng: 'By time,',
          transliteration: 'Wa-l-ʿaṣr',
        ),
        Ayah(
          surahNumber: 103,
          ayahNumber: 2,
          arabic: 'إِنَّ الْإِنسَانَ لَفِي خُسْرٍ',
          translationEng: 'Indeed, mankind is in loss,',
          transliteration: 'Inna l-insāna la-fī khusr',
        ),
        Ayah(
          surahNumber: 103,
          ayahNumber: 3,
          arabic: 'إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ',
          translationEng: 'Except for those who have believed and done righteous deeds and advised each other to truth and advised each other to patience.',
          transliteration: 'Illā lladhīna āmanū wa-ʿamilū ṣ-ṣāliḥāti wa-tawāṣaw bi-l-ḥaqqi wa-tawāṣaw bi-ṣ-ṣabr',
        ),
      ],
    ),
    108: Surah(
      number: 108,
      name: 'الكوثر',
      englishName: 'Al-Kawthar',
      revelationPlace: 'Meccan',
      ayahCount: 3,
      ayahs: [
        Ayah(
          surahNumber: 108,
          ayahNumber: 1,
          arabic: 'إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ',
          translationEng: 'Indeed, We have granted you, [O Muhammad], al-Kawthar.',
          transliteration: 'Innā aʿṭaynāka l-kawthar',
        ),
        Ayah(
          surahNumber: 108,
          ayahNumber: 2,
          arabic: 'فَصَلِّ لِرَبِّكَ وَانْحَرْ',
          translationEng: 'So pray to your Lord and sacrifice [to Him alone].',
          transliteration: 'Fa-ṣalli li-rabbika wa-nḥar',
        ),
        Ayah(
          surahNumber: 108,
          ayahNumber: 3,
          arabic: 'إِنَّ شَانِئَكَ هُوَ الْأَبْتَرُ',
          translationEng: 'Indeed, your enemy is the one cut off.',
          transliteration: 'Inna shāniʾaka huwa l-abtar',
        ),
      ],
    ),
    109: Surah(
      number: 109,
      name: 'الكافرون',
      englishName: 'Al-Kafirun',
      revelationPlace: 'Meccan',
      ayahCount: 6,
      ayahs: [
        Ayah(surahNumber: 109, ayahNumber: 1, arabic: 'قُلْ يَا أَيُّهَا الْكَافِرُونَ', translationEng: 'Say, “O disbelievers,', transliteration: 'Qul yā ayyuhā l-kāfirūn'),
        Ayah(surahNumber: 109, ayahNumber: 2, arabic: 'لَا أَعْبُدُ مَا تَعْبُدُونَ', translationEng: 'I do not worship what you worship.', transliteration: 'Lā aʿbudu mā taʿbudūn'),
        Ayah(surahNumber: 109, ayahNumber: 3, arabic: 'وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ', translationEng: 'Nor are you worshippers of what I worship.', transliteration: 'Wa-lā antum ʿābidūna mā aʿbud'),
        Ayah(surahNumber: 109, ayahNumber: 4, arabic: 'وَلَا أَنَا عَابِدٌ مَّا عَبَدتُّمْ', translationEng: 'Nor will I be a worshipper of what you worship.', transliteration: 'Wa-lā anā ʿābidun mā ʿabadtum'),
        Ayah(surahNumber: 109, ayahNumber: 5, arabic: 'وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ', translationEng: 'Nor will you be worshippers of what I worship.', transliteration: 'Wa-lā antum ʿābidūna mā aʿbud'),
        Ayah(surahNumber: 109, ayahNumber: 6, arabic: 'لَكُمْ دِينُكُمْ وَلِيَ دِينِ', translationEng: 'For you is your religion, and for me is my religion.”', transliteration: 'Lakum dīnukum wa-liya dīn'),
      ],
    ),
    110: Surah(
      number: 110,
      name: 'النصر',
      englishName: 'An-Nasr',
      revelationPlace: 'Medinan',
      ayahCount: 3,
      ayahs: [
        Ayah(surahNumber: 110, ayahNumber: 1, arabic: 'إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ', translationEng: 'When the victory of Allah has come and the conquest,', transliteration: 'Idhā jāʾa naṣru llāhi wa-l-fatḥ'),
        Ayah(surahNumber: 110, ayahNumber: 2, arabic: 'وَرَأَيْتَ النَّاسَ يَدْخُلُونَ فِي دِينِ اللَّهِ أَفْوَاجًا', translationEng: 'And you see the people entering into the religion of Allah in multitudes,', transliteration: 'Wa-raʾayta n-nāsa yadkhulūna fī dīni llāhi afwājā'),
        Ayah(surahNumber: 110, ayahNumber: 3, arabic: 'فَسَبِّحْ بِحَمْدِ رَبِّكَ وَاسْتَغْفِرْهُ ۚ إِنَّهُ كَانَ تَوَّابًا', translationEng: 'Then exalt [Him] with praise of your Lord and ask forgiveness of Him. Indeed, He is ever Accepting of repentance.', transliteration: 'Fa-sabbiḥ bi-ḥamdi rabbika wa-staghfirhu, innahu kāna tawwābā'),
      ],
    ),
    111: Surah(
      number: 111,
      name: 'المسد',
      englishName: 'Al-Masad',
      revelationPlace: 'Meccan',
      ayahCount: 5,
      ayahs: [
        Ayah(surahNumber: 111, ayahNumber: 1, arabic: 'تَبَّتْ يَدَا أَبِي لَهَبٍ وَتَبَّ', translationEng: 'May the hands of Abu Lahab be ruined, and ruined is he.', transliteration: 'Tabbat yadā abī lahabin wa-tabb'),
        Ayah(surahNumber: 111, ayahNumber: 2, arabic: 'مَا أَغْنَىٰ عَنْهُ مَالُهُ وَمَا كَسَبَ', translationEng: 'Neither his wealth nor what he earned will avail him.', transliteration: 'Mā aghnā ʿanhu māluhu wa-mā kasab'),
        Ayah(surahNumber: 111, ayahNumber: 3, arabic: 'سَيَصْلَىٰ نَارًا ذَاتَ لَهَبٍ', translationEng: 'He will [enter to] burn in a Fire of [blazing] flame', transliteration: 'Sa-yaṣlā nāran dhāta lahab'),
        Ayah(surahNumber: 111, ayahNumber: 4, arabic: 'وَامْرَأَتُهُ حَمَّالَةَ الْحَطَبِ', translationEng: 'And his wife [as well] - the carrier of firewood.', transliteration: 'Wa-mraʾatuhu ḥammālata l-ḥaṭab'),
        Ayah(surahNumber: 111, ayahNumber: 5, arabic: 'فِي جِيدِهَا حَبْلٌ مِّن مَّسَدٍ', translationEng: 'Around her neck is a rope of [twisted] fiber.', transliteration: 'Fī jīdihā ḥablun min masad'),
      ],
    ),
    112: Surah(
      number: 112,
      name: 'الإخلاص',
      englishName: 'Al-Ikhlas',
      revelationPlace: 'Meccan',
      ayahCount: 4,
      ayahs: [
        Ayah(surahNumber: 112, ayahNumber: 1, arabic: 'قُلْ هُوَ اللَّهُ أَحَدٌ', translationEng: 'Say, “He is Allah, [who is] One,', transliteration: 'Qul huwa llāhu aḥad'),
        Ayah(surahNumber: 112, ayahNumber: 2, arabic: 'اللَّهُ الصَّمَدُ', translationEng: 'Allah, the Sustainer [needed by all],', transliteration: 'Allāhu ṣ-ṣamad'),
        Ayah(surahNumber: 112, ayahNumber: 3, arabic: 'لَمْ يَلِدْ وَلَمْ يُولَدْ', translationEng: 'He neither begets nor is born,', transliteration: 'Lam yalid wa-lam yūlad'),
        Ayah(surahNumber: 112, ayahNumber: 4, arabic: 'وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ', translationEng: 'Nor is there to Him any equivalent.”', transliteration: 'Wa-lam yakun lahu kufuwan aḥad'),
      ],
    ),
    113: Surah(
      number: 113,
      name: 'الفلق',
      englishName: 'Al-Falaq',
      revelationPlace: 'Meccan',
      ayahCount: 5,
      ayahs: [
        Ayah(surahNumber: 113, ayahNumber: 1, arabic: 'قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ', translationEng: 'Say, “I seek refuge in the Lord of daybreak', transliteration: 'Qul aʿūdhu bi-rabbi l-falaq'),
        Ayah(surahNumber: 113, ayahNumber: 2, arabic: 'مِن شَرِّ مَا خَلَقَ', translationEng: 'From the evil of that which He created', transliteration: 'Min sharri mā khalaq'),
        Ayah(surahNumber: 113, ayahNumber: 3, arabic: 'وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ', translationEng: 'And from the evil of darkness when it settles', transliteration: 'Wa-min sharri ghāsiqin idhā waqab'),
        Ayah(surahNumber: 113, ayahNumber: 4, arabic: 'وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ', translationEng: 'And from the evil of the blowers in knots', transliteration: 'Wa-min sharri n-naffāthāti fī l-ʿuqad'),
        Ayah(surahNumber: 113, ayahNumber: 5, arabic: 'وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ', translationEng: 'And from the evil of an envier when he envies.”', transliteration: 'Wa-min sharri ḥāsidin idhā ḥasad'),
      ],
    ),
    114: Surah(
      number: 114,
      name: 'الناس',
      englishName: 'An-Nas',
      revelationPlace: 'Meccan',
      ayahCount: 6,
      ayahs: [
        Ayah(surahNumber: 114, ayahNumber: 1, arabic: 'قُلْ أَعُوذُ بِرَبِّ النَّاسِ', translationEng: 'Say, “I seek refuge in the Lord of mankind,', transliteration: 'Qul aʿūdhu bi-rabbi n-nās'),
        Ayah(surahNumber: 114, ayahNumber: 2, arabic: 'مَلِكِ النَّاسِ', translationEng: 'The Sovereign of mankind,', transliteration: 'Maliki n-nās'),
        Ayah(surahNumber: 114, ayahNumber: 3, arabic: 'إِلَٰهِ النَّاسِ', translationEng: 'The God of mankind,', transliteration: 'Ilāhi n-nās'),
        Ayah(surahNumber: 114, ayahNumber: 4, arabic: 'مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ', translationEng: 'From the evil of the retreating whisperer', transliteration: 'Min sharri l-waswāsi l-khannās'),
        Ayah(surahNumber: 114, ayahNumber: 5, arabic: 'الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ', translationEng: 'Who whispers [evil] into the breasts of mankind', transliteration: 'Alladhī yuwaswisu fī ṣudūri n-nās'),
        Ayah(surahNumber: 114, ayahNumber: 6, arabic: 'مِنَ الْجِنَّةِ وَالنَّاسِ', translationEng: 'From among the jinn and mankind.”', transliteration: 'Mina l-jinnati wa-n-nās'),
      ],
    ),
  };

  static List<Surah> get all => _surahs.values.toList();

  static Surah? byNumber(int n) => _surahs[n];

  static Surah? byName(String name) {
    for (final s in _surahs.values) {
      if (s.englishName == name || s.name == name) return s;
    }
    return null;
  }

  static int get count => _surahs.length;
}
