import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

import 'quran_models.dart';

/// The complete Qur'an, bundled offline as a trusted asset.
///
/// SOURCE: The Uthmani Arabic text follows the standard Hafs 'an 'Asim
/// orthography (the Tanzil text served by the quran.com project), with the
/// Saheeh International translation. Both are among the most widely accepted,
/// trusted sources. The full 114-surah dataset lives in
/// `assets/quran/quran.json` (generated by `tools/download_quran.py`).
///
/// IMPORTANT: Quranic text is fixed and trusted. Nothing in AyahPath ever
/// modifies or generates Quranic ayahs. The asset is only ever refreshed from
/// the trusted source — it is never produced by the AI.
class QuranDataset {
  QuranDataset._();

  static Map<int, Surah> _surahs = {};
  static bool _loaded = false;

  /// Loads the whole dataset from the bundled asset. Safe to call multiple
  /// times. Returns true once the data is available.
  static Future<void> load() async {
    if (_loaded) return;
    final raw = await rootBundle.loadString('assets/quran/quran.json');
    final decoded = jsonDecode(raw) as Map<String, dynamic>;
    final list = decoded['surahs'] as List<dynamic>;
    final map = <int, Surah>{};
    for (final entry in list) {
      final e = entry as Map<String, dynamic>;
      final ayahList = (e['ayahs'] as List<dynamic>).map((a) {
        final m = a as Map<String, dynamic>;
        return Ayah(
          surahNumber: e['number'] as int,
          ayahNumber: m['n'] as int,
          arabic: m['ar'] as String,
          translationEng: m['en'] as String?,
        );
      }).toList();
      map[e['number'] as int] = Surah(
        number: e['number'] as int,
        name: e['name'] as String,
        englishName: e['englishName'] as String,
        ayahCount: e['ayahCount'] as int,
        revelationPlace: e['revelationPlace'] == 'makkah' ? 'Meccan' : 'Medinan',
        ayahs: ayahList,
      );
    }
    _surahs = map;
    _loaded = true;
  }

  static List<Surah> get all => _surahs.values.toList();

  static Surah? byNumber(int n) => _surahs[n];

  static Surah? byName(String name) {
    for (final s in _surahs.values) {
      if (s.englishName == name || s.name == name) return s;
    }
    return null;
  }

  static int get count => _surahs.length;
}
